### ISSUE TITLE
Solution Name & Type

### ISSUE THREAD

**Issue by rhanoudi** [LucasHahne/PCF-MDA-Background-Control#5]
Hello,

Thanks for creating this great PCF control. I noticed 2 things:

1. The solutions are unmanaged. Can you provide a managed solution?
2. The solution name is "Solution". Is it possible to provide a better name?

Thanks!

**Comment by LucasHahne** [comment]
Hello,Yes I noticed that as well.Actually I am going to do some updates and recreate the solutions as managed and unmanaged in the near future.I am not sure when I will get time but I will update my GitHub with the new releases.Best regards Lucas--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 16.04.24, 21:46 schrieb rhanoudi ***@***.***>:

   
  Hello, 
  Thanks for creating this great PCF control. I noticed 2 things: 
   
   The solutions are unmanaged. Can you provide a managed solution? 
   The solution name is "Solution". Is it possible to provide a better name? 
   
  Thanks!

**Comment by LucasHahne** [comment]
Hello @rhanoudi 

I started reworking a lot of solutions and updated the readme.
I am still working on updating and providing all managed solutions
