### ISSUE TITLE
Cant Save Record after clearing DateOnly Field

### ISSUE THREAD

**Issue by r0man5k** [LucasHahne/PCF-MDA-Background-Control#6]
Hello Lucas,

thanks for the pcf controls.

When using the DateOnly Background Contol, i stumbled into the issue that
after trying to clear the date, it gives out an error and i cant save the form
any longer. 

So in other words, setting the field to date only field to  "dd/mm/yyyy" 
gives me an error when the "Save" button is pushed.

Thanks in adance for looking into it.

Regards,

Roman

**Comment by LucasHahne** [comment]
Hi Roman,

we have seen the issue as well and fixed it.
I have to upload the latest version for all my PCFs but had no time for it. 
I try uploading it soon.

**Comment by LucasHahne** [comment]
Hi @r0man5k ,

you should now be able to get the DatePCF and it should work properly.
Unfortunately you have to see if the timezone matches for you as it was implemented for UTC +2.
I will be updating the PCF so that all timezones are available later on

**Comment by r0man5k** [comment]
hi @LucasHahne

thank you so much for the quick response and the
fast resolve. it works fine now!
